version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: user-postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" #SMTP server
      - "8025:8025" #Web UI

volumes:
  postgres_data: